// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/afterparty-invitation-jp.tsx";
import * as $1 from "./routes/afterparty-jp-response.tsx";
import * as $2 from "./routes/afterparty-jp.tsx";
import * as $3 from "./routes/city-hall-ceremony.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/info.tsx";
import * as $6 from "./routes/invitation/[id].tsx";
import * as $7 from "./routes/photos.tsx";
import * as $8 from "./routes/response.tsx";
import * as $9 from "./routes/save-the-date.tsx";
import * as $10 from "./routes/thanks.tsx";
import * as $11 from "./routes/upload.tsx";
import * as $$0 from "./islands/LanguageButton.tsx";

const manifest = {
  routes: {
    "./routes/afterparty-invitation-jp.tsx": $0,
    "./routes/afterparty-jp-response.tsx": $1,
    "./routes/afterparty-jp.tsx": $2,
    "./routes/city-hall-ceremony.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/info.tsx": $5,
    "./routes/invitation/[id].tsx": $6,
    "./routes/photos.tsx": $7,
    "./routes/response.tsx": $8,
    "./routes/save-the-date.tsx": $9,
    "./routes/thanks.tsx": $10,
    "./routes/upload.tsx": $11,
  },
  islands: {
    "./islands/LanguageButton.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
